### ISSUE TITLE
Script fails to load

### ISSUE THREAD

**Issue by QuarterMileRP** [Mycroft-Studios/mycroft_cinema#2]
Quick question, and I probably already know the answer... does this require ESX 1.8.5 or higher? I'm getting the error
 "Error loading script client/main.lua in resource mycroft_cinema: @mycroft_cinema/shared/main.lua:199: attempt to call a nil value (field 'RegisterInput')
[   1345594] [FiveM_b2699_GT]             MainThrd/ stack traceback:
[   1345594] [FiveM_b2699_GT]             MainThrd/ 	@mycroft_cinema/shared/main.lua:199: in field 'RegisterInput'
[   1345594] [FiveM_b2699_GT]             MainThrd/ 	@mycroft_cinema/client/main.lua:178: in main chunk
[   1345594] [FiveM_b2699_GT]             MainThrd/ Failed to load script client/main.lua."
 I'm running v1.7.5 currently.. or is there something else I'm missing?

**Comment by Mycroft-Studios** [comment]
Requires 1.8.5 or higher,yes ,I'm not going to reduce the amount of features and the quality of features just because people don't want to use newer , better code lol

**Comment by Ricko0o** [comment]
All good Mycroft.. was just asking.. I met you a while back through Oso.. I know you know your scthuff.. :)
